networks:
  mqtt_network:  # Define a custom network
    driver: bridge

services:
  mosquitto:
    image: eclipse-mosquitto:latest
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto:/etc/mosquitto
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
#      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
    networks:
      - mqtt_network

  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile.gateway
    depends_on:
      - mosquitto
    networks:
      - mqtt_network

  node1:
    build:
      context: ./node
      dockerfile: Dockerfile.node
    depends_on:
      - mosquitto
    networks:
      - mqtt_network

  # node2:
  #   build:
  #     context: ./node
  #     dockerfile: Dockerfile.node
  #   depends_on:
  #     - mosquitto
  #   networks:
  #     - mqtt_network
