FROM alpine:latest AS build
RUN apk add --no-cache gcc musl-dev mosquitto-dev jansson-dev pkgconfig
WORKDIR /app
COPY node.c .
# RUN gcc -o gateway gateway.c
RUN gcc -o node node.c $(pkg-config --cflags --libs jansson libmosquitto) 

FROM alpine:latest
# Install only the runtime dependencies
RUN apk add --no-cache mosquitto jansson
WORKDIR /app
COPY --from=build /app/node .
CMD ["./node"]